print("----{Iniciando Programa}----")
print("\nDigite um Número: ")
numero = float(input())
print("\nDigite um segundo Número: ")
numero2 = float(input())
print("----{Processando... }----")
print("Multiplicando: {}".format(numero * numero2))
print("Dividindo: {}".format(numero / numero2))
print("Somando: {}".format(numero + numero2))
print("Subtraindo: {}".format(numero - numero2))